name: APP-STORE STABLE

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'SOURCES/'
        directory: 'PROGRAMS/PAPER-APP-STORE'
        filename: 'STABLE.ZIP'
        exclusions: ''

