name: APP-STORE STABLE

on:
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: PROGRAMS/PAPER-APP-STORE/SOURCES/
          dest: PROGRAMS/PAPER-APP-STORE/APPSTABLE.ZIP
